[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1"
serde_derive = { path = "../crates/serde_derive" }
serde_derive_next = { path = "../crates/serde_derive_next" }