[workspace]
members = [
  "bench",
  "crates/serde_derive",
  "crates/serde_derive_impl",
  "crates/serde_derive_next",
  "crates/serde_derive_next_impl", "example",
]
resolver = "2"


[profile.dev]
opt-level = 3

[profile.dev.package."*"]
opt-level = 3